language: rust
rust:
- stable

cache:
  timeout: 360
  cargo: true

before_cache:
  - chmod -R a+r $HOME/.cargo

end:

matrix:
  include:
    - os: linux
      end: TARGET=x86_64-unknown-linux-gnu
    - os: osx
      env: TARGET=i686-apple-darwin

script:
  - cargo build --verbose
  - cargo test --verbose


deploy:
  provider: releases
  api_key:
    secure: KHye76DKntuZvCFlf6blmZ/sogrAUFLhPzc8CtSlwxZRXEGkCkG/hycoyn/7IjsrV8dfppPwtSobkHy/yLAgtJL/vJ4kwkbmhzxwXMlFzeVewix+rdpuL5PVsZid/qLyosmTO77vjlx91TgLX4b9mDtW78hmo61lpZ9lC49kyjFDnG/gxrXCzxtSPBGUyTuQakIqUiPCvA3aO0WBzVxuSIzbCEcXaxxfc4nMZDJgl/kqHgEEoYWfj28lr1acidrJceSv1upbfGK5heSgaiqYIufeDy5ya5WPJEOXyfLBzY0+7mKxwpcJ9hmhJiHxU9AYCZ0ayGslMtLgwZY9Ve6BecDCDvqu4SQSay7egI99mNPKp0ET6VrVv4vtAAQf6740AEncmW18m1y4WjOA7yLAK+bMZ7uchqLM9OW5JbE+Kbuz5bFMhk7h0sjBnca/t0J+6z/ttcDlNQVhAJlyqvpsPxvBdzDBlYvwMg7pDH0Uj9dSohplqw+BH0BqAG7372o5boQfjJtH4SFowGIn2ggdCUYVvMeWGahYFAMG6XGMb3qYgyHBbNOI4ULssCVF9snCenpgfqsV95Pxk+BcHit8zM23R15sooTHYh8JI7Sb+/v3urRVQeDe9p4LHyu4Ur8Zr8FDP6pVqKifCZ9bfmLwHGA92mQyXUSCW0J+dqUjKNA=
  file_glob: true
  file: ${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.*
  on:
    repo: inosion/madato
    # condition: "$TRAVIS_RUST_VERSION = stable"
    tags: true
  skip_cleanup: true
  branches:
    only:
      - master

#notifications:
#  email:
#    on_success: never
