[package]
name = "markdown-tools"
version = "0.1.0"
authors = ["Ramon Buckland <ramon.buckland@inosion.com>"]


[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen    = "0.2"
serde           = "1.0"
serde_yaml      = "0.7"
indexmap        = "1.0.1"
linked-hash-map = "0.5.1"
